# Name of your workflow
name: Aruduino Build on push workflow

# Define the trigger events.
on: [push, check_run]

# Jobs run in parallel be default, each runs steps in sequence
jobs:
  # Build the ATMEGA-320P
  compile-sketch:
    runs-on: [ubuntu-latest]
    steps:  
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4.5.0
      - uses: arduino/compile-sketches@v1.1.0
        with:
          fqbn: arduino:avr:uno
          verbose: true
          sketch-paths: arduino/epaper_display
          libraries: |
            - name: SD
            - name: LowPower_LowPowerLab
            - name: EEPROM
              version: "2.0"
