# Name of your workflow
name: Aruduino Build on push workflow

# Define the trigger events.
on: [push, check_run]

# Jobs run in parallel be default, each runs steps in sequence
jobs:
  # Build the ATMEGA-320P
  compile-sketch:
    runs-on: [ubuntu-latest]
    steps:  
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1.1.0
        with:
          fqbn: arduino:avr:uno
          verbose: true
          sketch-paths: arduino/epaper_display
          libraries: |
            - name: SD
            - name: LowPower_LowPowerLab
            - name: Arduino_builtin

  # Test the python image transformation code
  test-convert-images:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Display Python version
        run: |
          PYTHONPATH="$PWD"/convert_images
          echo PYTHONPATH
          cd tests
          python -c "import sys; print(sys.version)"
          python run_tests.py

